version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
