name: Manual Merge Dependabot PRs

on:
  workflow_dispatch:

jobs:
  list-dependabot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: List Dependabot PRs
        run: |
          gh pr list --author dependabot[bot] --json number,title,url

  merge-dependabot-prs:
    needs: list-dependabot-prs
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PRs
        run: |
          prs=$(gh pr list --author dependabot[bot] --json number --jq '.[].number')
          for pr in $prs; do
            gh pr merge $pr --merge
          done
